version: '3.9'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: 'always'
    ports:
      - 5431:5432
    volumes:
      - quicksave_data:/var/lib/postgresql/data
    container_name: postgres_db

volumes:
  quicksave_data:
